### ISSUE TITLE
Fedora 28 - issue running make after ./configure

### ISSUE THREAD

**Issue by MathieuBordere** [excamera/alfalfa#74]
Hi,

First of all, a big thank you for making the source code for this exciting project available.
I'm trying to build and install Salsify using the steps described in the README.
For some, reason, `make` fails with the following output.

> lati :: ~/code/alfalfa ‹master*› » make -j4
make  all-recursive
make[1]: Entering directory '/home/mathieu/code/alfalfa'
Making all in src
make[2]: Entering directory '/home/mathieu/code/alfalfa/src'
Making all in util
make[3]: Entering directory '/home/mathieu/code/alfalfa/src/util'
  CXX      file.o
  CXX      ivf.o
  CXX      raster.o
  CXX      ssim.o
  CXX      ivf_writer.o
  CXX      mmap_region.o
  CXX      paranoid.o
  CXX      procinfo.o
  AR       libalfalfautil.a
make[3]: Leaving directory '/home/mathieu/code/alfalfa/src/util'
Making all in decoder
make[3]: Entering directory '/home/mathieu/code/alfalfa/src/decoder'
  CXX      decoder.o
  CXX      safe_raster.o
  CXX      loopfilter.o
  CXX      frame.o
  CXX      macroblock.o
  CXX      modemv_data.o
  CXX      prediction.o
  CXX      quantization.o
  CXX      tokens.o
  CXX      transform.o
  CXX      tree.o
  CXX      uncompressed_chunk.o
  CXX      vp8_prob_data.o
yasm -f elf64 -I./../asm/ loopfilter_sse2.asm
yasm -f elf64 -I./../asm/ loopfilter_block_sse2_x86_64.asm
yasm -f elf64 -I./../asm/ subpixel_ssse3.asm
yasm -f elf64 -I./../asm/ idctllm_mmx.asm
yasm -f elf64 -I./../asm/ intrapred_ssse3.asm
yasm -f elf64 -I./../asm/ intrapred_sse2.asm
yasm -f elf64 -I./../asm/ fwalsh_sse2.asm
yasm -f elf64 -I./../asm/ subtract_sse2.asm
yasm -f elf64 -I./../asm/ sad_sse2.asm
yasm -f elf64 -I./../asm/ iwalsh_sse2.asm
yasm -f elf64 -I./../asm/ dct_sse2.asm
  CXX      raster_handle.o
  CXX      player.o
  CXX      probability_tables.o
  CXX      dct.o
yasm -f elf64 -I./../asm/ config.asm
yasm -f elf64 -I./../asm/ x86inc.asm
yasm -f elf64 -I./../asm/ x86_abi_support.asm
  CXX      frame_pool.o
  AR       libalfalfadecoder.a
make[3]: Leaving directory '/home/mathieu/code/alfalfa/src/decoder'
Making all in display
make[3]: Entering directory '/home/mathieu/code/alfalfa/src/display'
  CXX      gl_objects.o
  CXX      display.o
  AR       libalfalfadisplay.a
make[3]: Leaving directory '/home/mathieu/code/alfalfa/src/display'
Making all in input
make[3]: Entering directory '/home/mathieu/code/alfalfa/src/input'
  CXX      ivf_reader.o
  CXX      yuv4mpeg.o
  CXX      camera.o
  AR       libalfalfainput.a
make[3]: Leaving directory '/home/mathieu/code/alfalfa/src/input'
Making all in encoder
make[3]: Entering directory '/home/mathieu/code/alfalfa/src/encoder'
  CXX      variance.o
  CXX      variance_sse2.o
  CXX      safe_references.o
  CXX      costs.o
  CXX      serializer.o
  CXX      encode_tree.o
  CXX      encoder.o
  CXX      encode_intra.o
  CXX      encode_inter.o
  CXX      reencode.o
  CXX      size_estimation.o
  AR       libalfalfaencoder.a
make[3]: Leaving directory '/home/mathieu/code/alfalfa/src/encoder'
Making all in net
make[3]: Entering directory '/home/mathieu/code/alfalfa/src/net'
  CXX      address.o
  CXX      socket.o
  CXX      socketpair.o
  CXX      packet.o
  CXX      poller.o
  AR       libnet.a
make[3]: Leaving directory '/home/mathieu/code/alfalfa/src/net'
Making all in frontend
make[3]: Entering directory '/home/mathieu/code/alfalfa/src/frontend'
  CXX      vp8decode.o
  CXX      xc-enc.o
  CXX      xc-ssim.o
  CXX      xc-dissect.o
  CXX      xc-framesize.o
  CXX      xc-dump.o
  CXX      xc-diff.o
  CXX      comp-states.o
  CXX      decode-bundle.o
  CXX      xc-merge.o
  CXX      xc-terminate-chunk.o
  CXX      vp8play-vp8play.o
  CXX      xc-zero-out-residues.o
  CXXLD    vp8decode
  CXXLD    xc-enc
  CXXLD    xc-ssim
  CXXLD    xc-dissect
xc-enc.o: In function `std::unique_ptr<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >, FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > > >::~unique_ptr()':
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > >::operator()(Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > >::operator()(Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >*) const'
xc-enc.o: In function `std::unique_ptr<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >, FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > > >::~unique_ptr()':
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > >::operator()(Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > >::operator()(Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >*) const'
../encoder/libalfalfaencoder.a(encoder.o): In function `std::unique_ptr<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >, FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > > >::reset(Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >*)':
/usr/include/c++/8/bits/unique_ptr.h:382: undefined reference to `FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > >::operator()(Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >*) const'
/usr/include/c++/8/bits/unique_ptr.h:382: undefined reference to `FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > >::operator()(Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >*) const'
../encoder/libalfalfaencoder.a(encoder.o): In function `std::unique_ptr<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >, FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > > >::reset(Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >*)':
/usr/include/c++/8/bits/unique_ptr.h:382: undefined reference to `FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > >::operator()(Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >*) const'
/usr/include/c++/8/bits/unique_ptr.h:382: undefined reference to `FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > >::operator()(Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >*) const'
../encoder/libalfalfaencoder.a(encoder.o): In function `std::unique_ptr<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >, FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > > >::~unique_ptr()':
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > >::operator()(Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > >::operator()(Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > >::operator()(Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > >::operator()(Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >*) const'
../encoder/libalfalfaencoder.a(encoder.o): In function `std::unique_ptr<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >, FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > > >::~unique_ptr()':
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > >::operator()(Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > >::operator()(Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > >::operator()(Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > >::operator()(Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > >::operator()(Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >*) const'
../encoder/libalfalfaencoder.a(encoder.o):/usr/include/c++/8/bits/unique_ptr.h:274: more undefined references to `FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > >::operator()(Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >*) const' follow
../encoder/libalfalfaencoder.a(encoder.o): In function `std::unique_ptr<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >, FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > > >::~unique_ptr()':
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > >::operator()(Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > >::operator()(Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >*) const'
../encoder/libalfalfaencoder.a(encoder.o): In function `std::unique_ptr<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >, FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > > >::~unique_ptr()':
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > >::operator()(Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > >::operator()(Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >*) const'
../encoder/libalfalfaencoder.a(encoder.o): In function `std::unique_ptr<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >, FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > > >::~unique_ptr()':
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > >::operator()(Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > >::operator()(Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >*) const'
../encoder/libalfalfaencoder.a(encoder.o): In function `std::unique_ptr<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >, FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > > >::~unique_ptr()':
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> > >::operator()(Frame<InterFrameHeader, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> >*) const'
../encoder/libalfalfaencoder.a(encoder.o): In function `std::unique_ptr<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >, FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > > >::~unique_ptr()':
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > >::operator()(Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `FrameDeleter<Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> > >::operator()(Frame<KeyFrameHeader, Macroblock<KeyFrameHeader, KeyFrameMacroblockHeader> >*) const'
../encoder/libalfalfaencoder.a(encoder.o): In function `std::unique_ptr<SafeRaster, RasterDeleter<SafeRaster> >::~unique_ptr()':
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `RasterDeleter<SafeRaster>::operator()(SafeRaster*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `RasterDeleter<SafeRaster>::operator()(SafeRaster*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `RasterDeleter<SafeRaster>::operator()(SafeRaster*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `RasterDeleter<SafeRaster>::operator()(SafeRaster*) const'
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `RasterDeleter<SafeRaster>::operator()(SafeRaster*) const'
../encoder/libalfalfaencoder.a(encoder.o):/usr/include/c++/8/bits/unique_ptr.h:274: more undefined references to `RasterDeleter<SafeRaster>::operator()(SafeRaster*) const' follow
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:535: xc-enc] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/mathieu/code/alfalfa/src/frontend'
make[2]: *** [Makefile:375: all-recursive] Error 1
make[2]: Leaving directory '/home/mathieu/code/alfalfa/src'
make[1]: *** [Makefile:424: all-recursive] Error 1
make[1]: Leaving directory '/home/mathieu/code/alfalfa'
make: *** [Makefile:356: all] Error 2

When I run `./configure --enable-debug` prior to `make` instead of `./configure` without flags, compilation succeeds.

**Comment by sadjad** [comment]
Thank you for bringing this into our attention. There was a problem in building alfalfa with GCC 8 and it's now fixed.

–Sadjad
