### ISSUE TITLE
Executing salsify-receiver opens player but stops working immediately

### ISSUE THREAD

**Issue by jmerizia** [excamera/alfalfa#75]
Hello!

This is a very interesting project! Wish I heard about it sooner. I tried to run the demo, but I ran into a problem at the very end.

Long story short: After setup and installation, when I run `salsify-receiver 3000 1280 720` the player will open but immediately gives the warning `"VP8 Player" is not working. You may choose to wait a short while for it to continue or force the application to quit entirely.`, with options to force quit or wait.

I'm currently running Fedora 27. I went through the build instructions, installing the corresponding `dnf` packages. Here is a list of the packages that I definitely have installed:

- `g++` @>=5
- `yasm` and `yasm-devel`
- `libXinerama` and `libXinerama-devel`
- `libXcursor` and `libXcursor-devel`
- `mesa-libGLU` and `mesa-libGLU-devel`
- `boost` and `boost-devel`
- `x264` and `x264-devel`
- `libXrandr` and `libXrandr-devel`
- `libXi` and `libXi-devel`
- `glew` and `glew-devel`
- `derelict-GLFW3` and `derelict-GLFW3-devel`

There are more, but I believe this covers all the required packages since compilation ran smoothly.

It is also worth mentioning that running `salsify-sender /dev/video0 localhost 3000 1337` throws a `getaddrinfo: Servname not supported for ai_socktype` error, but I believe this is most likely because the receiver is never properly run.
**Note:** I tried multiple ports and made sure they were not being used.

**Comment by sadjad** [comment]
Hi Jacob,

As for the receiver, you can ignore that warning. The system *thinks* that the receiver has stopped working, but it has not.

As for the sender, the correct command line is `salsify-sender -d /dev/video0 localhost 3000 1337`. You're missing that `-d` in the arguments before the video device!

Let me know if you run into any other problems!

—Sadjad
