### ISSUE TITLE
Compile Error on Ubuntu 18.04LTS

### ISSUE THREAD

**Issue by oooanoonymoous** [excamera/alfalfa#82]
Hello, 

I try to compile alfalfa on my laptop but fail to do so. All required libraries are satisfied. Here is error code:

`
Making all in frontend
make[3]: Entering directory '/home/anonymous/Downloads/alfalfa/src/frontend'
  CXXLD    vp8play
/usr/bin/ld: /usr/local/lib/libglfw3.a(posix_thread.c.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:515: recipe for target 'vp8play' failed
make[3]: *** [vp8play] Error 1
make[3]: Leaving directory '/home/anonymous/Downloads/alfalfa/src/frontend'
Makefile:376: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/anonymous/Downloads/alfalfa/src'
Makefile:425: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/anonymous/Downloads/alfalfa'
Makefile:357: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by oooanoonymoous** [comment]
Just adding all necessary required libs, it will compile fine!

**Comment by kanonjz** [comment]
Hi, I met the same problem. Could you explain how to solve the problem a bit more? Do I miss install some packages?

**Comment by sadjad** [comment]
Hi @kanonjz,

Are you trying to build this on Ubuntu?

--Sadjad

**Comment by kanonjz** [comment]
Yes, I'm trying to build this on Ubuntu 18.04.

**Comment by kanonjz** [comment]
Hi @sadjad, do you have any suggestions for this problem? Thanks.

**Comment by sadjad** [comment]
Do you have all the packages [listed in the README](https://github.com/excamera/alfalfa#build-directions) installed?
