### ISSUE TITLE
build error on MacOS xcode-select version 2373.

### ISSUE THREAD

**Issue by ShuaiZhao** [excamera/alfalfa#83]
./configure error on MacOS

configure: error: Package requirements (gl) were not met:

No package 'gl' found

**Comment by keithw** [comment]
I don't think we've tried to run this on Mac OS -- it probably needs to be ported.

**Comment by ShuaiZhao** [comment]
@keithw thanks for your reply. What systems have you tried?

**Comment by keithw** [comment]
It was developed on GNU/Linux. Probably could be gotten to work on most FOSS BSDs as well.

**Comment by ShuaiZhao** [comment]
okie. 
FYI, the following solves the configure issues.
PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/X11/lib/pkgconfig

however, there are still issue when  $make, complaining endian.h file not found...
