### ISSUE TITLE
Adding QRcode

### ISSUE THREAD

**Issue by skywalker1996** [excamera/alfalfa#90]
Hello, author, thanks for your contribution! I noticed that in Salsify's paper, it adds QR codes both in the sender's frames and receiver's frames, but I didn't find related codes in this repo. Does this repo contain testbed programs?

**Comment by keithw** [comment]
Thanks for your kind words! The testing infrastructure was used for **all** of the compared schemes (Salsify, Skype, FaceTime, WebRTC, Google Hangouts) and so is not part of the Salsify repo. You can find that code at https://github.com/excamera/Captain-EO . The barcoder specifically is in https://github.com/excamera/Captain-EO/tree/master/src/barcoder

It's not a QR code -- just a very simple two-dimensional 8x8 barcode. We applied the barcode to the raw test video upfront and then sent the same test video through Salsify, Skype, FaceTime, WebRTC, etc. -- it is not applied in real time by any of these programs.
